services:
  - type: web
    name: almas-dimas-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://your-backend.onrender.com/api
      - key: VITE_APP_NAME
        value: ALMAS & DIMAS
      - key: VITE_APP_VERSION
        value: 1.0.0

